config/routes.rb
Rails.application.routes.draw do


  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'weibo'  => 'sessions#weibo'
  get    'github' => 'sessions#github'

  resources :users
  get 'signup' => 'users#new'

  resources :topics
  resources :members

  root 'static_pages#home'
  get 'about' => 'static_pages#about'

  resources :wechat
  resources :wechatmenu

end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_admin, only: [:new, :edit, :update]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all.order(:time).reverse_order.paginate(page:params[:page])
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html do
          redirect_to @topic
          flash[:success] = 'Topic was successfully created.'
        end
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html do
          redirect_to @topic
          flash[:success] = 'Topic was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html {render :edit}
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html do
        redirect_to topics_url
        flash[:success] = 'Topic was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:topic_id, :topic_type, :time, :title, :content)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <form>
    <div class="row">
      <div class="form-group col-md-6 col-md-offset-3">
        <%= f.label "Topic ID" %><br>
        <%= f.text_field :topic_id,class:"form-control" %><br>

        <%= f.label :topic_type %><br>
        <%= f.select(:topic_type, options_for_select([["1-战报", 1], ["2-活动", 2], ["3-专访", 3], ["4-公告", 4], ["5-其他", 5]], 5), {}, {class:"form-control"})%><br>

        <%= f.label :time %><br>
        <%= f.date_select :time, {}, {:class => 'date-select'} %><br><br>

        <%= f.label :title %><br>
        <%= f.text_field :title,class:"form-control" %><br>

        <%= f.label :content %><br>
        <%= f.text_area :content,class:"form-control", :rows => "10" %><br>

        <%= f.submit "Submit", class:"btn btn-primary"%>
      </div>
    </div>
    </form>
<% end %>

app/views/topics/_topic.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="well"><%= link_to(topic) do %>
        <h3><%= topic.title %><small><%= topic.time.to_s %></small></h3>
    <% end %>
        <%= truncate(topic.content, :length => 300) %>
    </div>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>


<% if @topics.any? %>
    <div class="col-md-offset-1">
      <h3>Topics (<%= @topics.count %>)</h3>
    </div>

  <div class="row">
    <%= render @topics %>
  </div>
  <%= will_paginate @topics %>
<% end %>

<% if is_admin? %>
    <div class="col-md-offset-1">
      <%= link_to 'New Topic', new_topic_path %>
    </div>
<% end %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<div class="page-header">
  <h1 class="title"><%= @topic.title %></h1>
  <div class="center"><%= @topic.time.to_s %></div>
</div>

<div class="row">
  <div class="well col-md-10 col-md-offset-1">
    <%= render html: @topic.content.gsub(/\n/, '<br>').html_safe %><br><br>
  </div>
</div>




<div class="row">
  <div class="btn-group col-md-offset-1 col-sm-6 col-sm-offset-0 col-xs-10 col-xs-offset-1">
    <%= link_to 'Back', topics_path, :class => " btn btn-default"%>
    <% if is_admin? %>
      <%= link_to 'Edit', edit_topic_path(@topic), :class => " btn btn-default"%>
      <%= link_to 'Destroy', @topic, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => 'color: #FFFFFF'%>
    <% end %>

  </div>
</div>