config/routes.rb
Rails.application.routes.draw do


  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'weibo'  => 'sessions#weibo'
  get    'github' => 'sessions#github'

  resources :users
  get 'signup' => 'users#new'

  resources :topics
  resources :members

  root 'static_pages#home'
  get 'about' => 'static_pages#about'

  resources :wechat
  resources :wechatmenu

end

app/views/layouts/_alert.html.erb
<% flash.each do |key, value| %>
    <div class="alert <%= flash_class(key) %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= value %>
    </div>
<% end %>

<script>
    //$(".alert-dismissible").delay(3000).fadeOut(500)
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    中大懂球帝 by <a href="https://github.com/BILLYHO/DongQiuDi">BILLY</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="https://github.com/BILLYHO">Contact</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "中大懂球帝", root_path, id: "logo" %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Members",   members_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <!--<li><%= link_to "Settings", '#' %></li>-->
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:wb="http://open.weibo.com/wb">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/alert' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>